FROM node:16-alpine

ENV NODE_ENV=production

# https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine
RUN apk add --no-cache libc6-compat

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

COPY tsconfig.json ./tsconfig.json

RUN yarn install --frozen-lockfile

COPY config ./config

COPY src ./src

RUN yarn build

CMD ["node", "dist/src/app.js"]
