FROM node:16-alpine

ENV NODE_ENV=production

ENV NEXT_PUBLIC_SERVER_ENDPOINT=http://localhost:1337

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

COPY tsconfig.json ./tsconfig.json

RUN yarn install --frozen-lockfile

COPY config ./config

COPY src ./src

RUN yarn build

CMD ["node", "dist/src/app.js"]
